import Shoes1 from "./img/pngwing.com 11.png";
import Shoes2 from "./img/pngwing.com 12.png";
import Shoes3 from "./img/pngwing.com 13.png";
import Shoes4 from "./img/pngwing.com 14.png";
import Shoes5 from "./img/pngwing.com 15.png";
import Shoes6 from "./img/pngwing.com 10.png";
import Shoes7 from "./img/pngwing.com 17.png";
import Shoes8 from "./img/pngwing.com 18.png";
import Shoes9 from "./img/pngwing.com 9.png";
import Shoes10 from "./img/pngwing.com 8.png";
const mainData = [
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes1,
    pris: 200,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "44",
    imgurl: Shoes2,
    pris: 210,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes3,
    pris: 220,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes4,
    pris: 260,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "41",
    imgurl: Shoes5,
    pris: 280,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes6,
    pris: 300,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "44",
    imgurl: Shoes7,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes8,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes9,
    pris: 250,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "41",
    imgurl: Shoes10,
    pris: 270,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes1,
    pris: 200,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "44",
    imgurl: Shoes2,
    pris: 210,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes3,
    pris: 220,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes4,
    pris: 260,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "41",
    imgurl: Shoes5,
    pris: 280,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes6,
    pris: 300,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "44",
    imgurl: Shoes7,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes8,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes9,
    pris: 250,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "41",
    imgurl: Shoes10,
    pris: 270,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes1,
    pris: 200,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "44",
    imgurl: Shoes2,
    pris: 210,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes3,
    pris: 220,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes4,
    pris: 260,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "41",
    imgurl: Shoes5,
    pris: 280,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes6,
    pris: 300,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "44",
    imgurl: Shoes7,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes8,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes9,
    pris: 250,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "41",
    imgurl: Shoes10,
    pris: 270,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes1,
    pris: 200,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "44",
    imgurl: Shoes2,
    pris: 210,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes3,
    pris: 220,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes4,
    pris: 260,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "41",
    imgurl: Shoes5,
    pris: 280,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Nike",
    size: "45",
    imgurl: Shoes6,
    pris: 300,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Adidas",
    size: "44",
    imgurl: Shoes7,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Poma",
    size: "43",
    imgurl: Shoes8,
    pris: 180,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Fashon",
    size: "42",
    imgurl: Shoes9,
    pris: 250,
  },
  {
    id: `${Math.random()}`,
    num: 0,
    prand: "Active",
    size: "41",
    imgurl: Shoes10,
    pris: 270,
  },
];
export default mainData;
